name: Restart Scheduler

on:
  workflow_run:
    workflows: ["Run Scheduler"]
    types:
      - completed

jobs:
  restart:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Run Scheduler completed, triggering restart..."
