name: Run Scheduler

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Run Restarter"]  
    types:
      - completed 

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          
      - name: Install Kaggle CLI
        run: |
          rm -rf ~/.kaggle
          rm -rf ~/.config/kaggle
          pip install 'kaggle> 1.6.17'

  
      - name: Test Kaggle authentication
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run:
          python lstm_scheduler.py
          
